version: "3"
services:
  frontend:
    container_name: an-ma-web-frontend
    build: 
      context: ./client
      dockerfile: Dockerfile
    image: mos/an-ma-web-frontend
    ports: 
      - "3000:3000"
    volumes: 
      - ./client:/user/src/app
  backend:
    container_name: an-ma-web-backend
    build: 
      context: ./server
      dockerfile: Dockerfile
    image: mos/an-ma-web-backend
    ports: 
      - "5000:5000"
    volumes: 
      - ./server:/user/src/app
